# Generated by Django 5.1.6 on 2025-02-11 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Exam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.CharField(default='<function uuid4 at 0x7f8042ea44a0>', editable=False, max_length=36, primary_key=True, serialize=False)),
                ('level', models.CharField(max_length=50)),
                ('term', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third')], max_length=10)),
                ('level_description', models.CharField(max_length=50)),
                ('total_number_of_students', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(default='<function uuid4 at 0x7f8042ea44a0>', editable=False, max_length=36, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('admission_number', models.CharField(max_length=10, unique=True)),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scoresheet',
            fields=[
                ('id', models.CharField(default='<function uuid4 at 0x7f8042ea44a0>', editable=False, max_length=36, primary_key=True, serialize=False)),
                ('attendance', models.IntegerField(default=0)),
                ('assignment', models.IntegerField(default=0)),
                ('test', models.IntegerField(default=0)),
                ('exam', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('grade', models.CharField(default='F9', max_length=2)),
                ('year', models.IntegerField(default=2025)),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Students.level')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Exam.subject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.student')),
            ],
            options={
                'indexes': [models.Index(fields=['year'], name='Students_sc_year_a24f66_idx'), models.Index(fields=['year', 'student'], name='Students_sc_year_243c33_idx'), models.Index(fields=['year', 'subject'], name='Students_sc_year_a2c652_idx'), models.Index(fields=['year', 'subject', 'level'], name='Students_sc_year_4e0a51_idx')],
            },
        ),
    ]
