# Generated by Django 5.1.6 on 2025-02-11 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdminStaff', '0001_initial'),
        ('Exam', '0001_initial'),
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.level'),
        ),
        migrations.AddField(
            model_name='solvedquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.question'),
        ),
        migrations.AddField(
            model_name='solvedquestion',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.student'),
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminStaff.teacher'),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.subject'),
        ),
        migrations.AddField(
            model_name='subjectscoresheet',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Students.level'),
        ),
        migrations.AddField(
            model_name='subjectscoresheet',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Exam.subject'),
        ),
    ]
